config/routes.rb
GroceryWrangler::Application.routes.draw do
  get "modal/category_selection"

  root 'users#index'

  resources :users, only: [:create, :index, :new]
  resources :store_items, only: [:create, :new, :show]
  resources :sessions, only: [:create]
  resources :receipt_items, only: [:destroy]
  resources :receipts
  resources :categories

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/budgeting',    to: 'budgeting#index',                          via: 'get'
  match '/price_trend',   to: 'price_trend#index',                       via: 'get'
  match '/recipes', to: 'recipe#index',                                  via: 'get'
  match '/category_selection_dialog', to: 'categories#selection_dialog', via: 'get'

  match '/receipt_add_items', to: 'receipts#add_items', via: 'post'
  match '/receipt_items_selection_dialog', to: 'receipt_items#selection_dialog', via: 'get'
  match '/receipt_items', to: 'receipt_items#update', via: 'patch'
end

app/models/receipt_item.rb
class ReceiptItem < ActiveRecord::Base
  before_save :update_total
  before_destroy :total_after_removal

  belongs_to :receipt
  belongs_to :store_item

  validates :price, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10000000 }, presence: true
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10000000 }
  validate :store_item_id_not_changed

  def update_quantity(quantity)
    self.quantity += quantity
    self.save!
  end

  private
  def total_after_removal
    @receipt = Receipt.find_by_id(self.receipt_id)

    if @receipt
      @receipt.total -= self.quantity * self.price
      @receipt.save!
    end
  end

  # TODO: BULK UPDATE!
  def update_total
    old_quantity = self.quantity_was || 0.0
    old_price = self.price_was || 0.0
    new_quantity = self.quantity
    new_price = self.price

    @receipt = Receipt.find_by_id(self.receipt_id)
    
    if @receipt
      delta_q = new_quantity - old_quantity
      delta_p = new_price - old_price

      @receipt.total += (old_quantity * delta_p) + delta_q * (old_price + delta_p)
      @receipt.save!
    end
  end
  
  def store_item_id_not_changed
    if self.store_item_id_changed? && self.persisted?
      errors.add(:store_item_id, "Change of receipt_item.store_item_id not allowed!")
    end
  end
end

app/controllers/receipt_items_controller.rb
class ReceiptItemsController < ApplicationController

  # DELETE /receipt_items
  def destroy
    @receipt_item = ReceiptItem.find(params[:id])
    @receipt = Receipt.find_by_id(@receipt_item.receipt_id)
    @receipt_item.destroy
    @receipt.reload
  end

  # GET /receipt_items_selection_dialog
  def selection_dialog
    @category = Category.find(params[:category])
    @receipt = Receipt.find(params[:receipt])
    @store_items = @category.store_items.where(store_id: @receipt.store_id)

    respond_to do |format|
      format.js 
    end
  end

  # PATCH /receipt_items/#
  def update
    @receipt_item = ReceiptItem.find(params[:receipt_item][:id])
    @receipt = Receipt.find_by_id(@receipt_item.receipt_id)

    @old_price = @receipt_item.price
    @old_quantity = @receipt_item.quantity
    
    if @receipt_item.update_attributes(receipt_item_params)
      respond_to do |format|
        @receipt.reload
        format.js
      end
    else
      respond_to do |format|
        format.js {head :ok}
      end      
    end
  end

  private 
  def receipt_item_params
    params.require(:receipt_item).permit(:quantity, :price)
  end
end

app/helpers/receipt_items_helper.rb
module ReceiptItemsHelper

  def cancel_edit_button()
    class_string = "cancel-edit-item-btn hide btn btn-sm btn-danger glyphicon glyphicon-ban-circle"
    button_tag("", type: "button", class: class_string)
  end

  def edit_button()
    class_string = "edit-item-btn btn btn-primary btn-sm glyphicon glyphicon-edit"

    button_tag("", type: "button", class: class_string)
  end

  def delete_button(id)
    class_string = "delete-item-btn btn btn-sm btn-danger glyphicon glyphicon-remove pull-right"
    link_to("", 
            receipt_item_path(id), 
            class: class_string, 
            method: :delete, 
            remote: true)
  end

  def save_button()
    class_string = "save-item-btn hide btn btn-success btn-sm glyphicon glyphicon-floppy-disk"
    button_tag("", class: class_string)
  end
end

app/views/receipt_items/_item_table_entry.html.erb
<% receipt_items.each do |receipt_item|%>
<tr id=<%= "receipt-table-item-#{receipt_item.id}" %>>
  <td class="hide">
    <%= text_field :receipt_item, :id, value: receipt_item.id, class: "hide item-table-id", size: 4 %>
  </td>

  <td class="receipt-td-align-left">
    <div class="btn-group">
      <%= save_button %> 
      <%= edit_button %>
      <%= cancel_edit_button %>
    </div>
  </td>

  <td class="td-centered"> <span><%= receipt_item.store_item.name %></span> </td>     
  <td class="td-centered"> 
    <% if receipt_item.store_item.category %>
    <span> <%= receipt_item.store_item.category.name %> </span>
    <% end %>
  </td>
  <td class="td-centered"> 
    <span class="item-table-quantity-text" id=<%="item_quantity_#{receipt_item.id}"%>> <%= string_to_int_or_float(receipt_item.quantity) %> </span>
    <%= text_field :receipt_item, :quantity, class: "hide item-table-quantity", size: 4 %>
</td>
  <td class="td-centered"> <span><%= receipt_item.store_item.weight %></span> </td>
  <td class="td-centered"> <span><%= receipt_item.store_item.volume %></span> </td>
  <td class="td-centered" %>
    <span class="item-table-price-text"id=<%="item_price_#{receipt_item.id}"%>>
      <%= price_string_format(receipt_item.price) %>
    </span>
    <%= text_field :receipt_item, :price, class: "hide item-table-price", size: 5 %>
  </td>
  <td>
    <%= delete_button  receipt_item.id%>
  </td>
</tr>
<% end %>

app/views/receipt_items/_selection_dialog.html.erb
<%= form_tag receipt_add_items_path(receipt: @receipt), remote: true do %>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
    </tr>
  </thead>
  <tbody>
    <% @store_items.each do |item| %>
    <tr>
      <td><%= check_box_tag "item_ids[]", item.id, false, id: "item_id_#{item.id}" %></td>
      <td><%= item.name %></td>
      <td> <%= text_field_tag "store_item_price_#{item.id}", '', maxlength: 15, class: "form-control input-sm", placeholder: "$"%></td>
      <td> 
	<%= select_tag "quantity_item_#{item.id}", options_for_select(Hash[(1..10).map { |num| [num, "#{num}"]}]), class: "selectpicker required"%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= submit_tag "Add Items", class: "btn btn-default", id: "modal-add-items" %>
<% end %>