config/routes.rb
GroceryWrangler::Application.routes.draw do
  get "modal/category_selection"

  root 'users#index'

  resources :users, only: [:create, :index, :new]
  resources :store_items, only: [:create, :new, :show]
  resources :sessions, only: [:create]
  resources :receipt_items, only: [:destroy]
  resources :receipts
  resources :categories

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/budgeting',    to: 'budgeting#index',                          via: 'get'
  match '/price_trend',   to: 'price_trend#index',                       via: 'get'
  match '/recipes', to: 'recipe#index',                                  via: 'get'
  match '/category_selection_dialog', to: 'categories#selection_dialog', via: 'get'

  match '/receipt_add_items', to: 'receipts#add_items', via: 'post'
  match '/receipt_items_selection_dialog', to: 'receipt_items#selection_dialog', via: 'get'
  match '/receipt_items', to: 'receipt_items#update', via: 'patch'
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :create_remember_token
  before_save { self.email = email.downcase }

  has_secure_password

  has_many :receipts, dependent: :destroy
  validates :name,  presence: true, length: {maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[A-Za-z\d\-.]+\.[a-zA-Z]+\z/
  validates :email, presence: true, length: {maximum: 50}, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: {minimum: 6}

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Successfully logged in."
      redirect_to root_url
    else
      @errors = @user.errors
      render 'new'
    end    
  end

  def index
  end

  def new
    @user = User.new
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/users/index.html.erb
<% provide(:title, 'GroceryWrangler') %>

<div class="jumbotron">
  <div class="container">
    <h1> Get Going With GroceryWrangler! </h1>
    <p> With GroceryWrangler you have the ability to easily track 
      your grocery purchasing habits.
      Simply create a receipt and add the items you bought to the receipt. 
      If you don't see an item you can easily create it!
    </p>

    <% if not signed_in? %>
    <p> 
      <a href=<%= signup_url %> class="btn btn-primary btn-lg" role="button"> Sign up now! &raquo; </a> 
    </p>
    <% end %>

  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4">
	    <%= image_tag("subheader-purchases.png", :alt => "", :class => "section-head") %>
      <h2>Track purchases</h2>
      <p>
	Check what price you've previously purchased items for and compare it with the price the stores are currently selling it for.
      </p>
      <p><a class="btn btn-default" href=<%= new_receipt_url %> role="button"> Get Started! &raquo;</a></p>
    </div>
    <div class="col-md-4">
	    <%= image_tag("subheader-trends.png", :alt => "", :class => "section-head") %>
      <h2>View seasonal trends</h2>
      <p> Under construction. </p>
      <p><a class="btn btn-default" href="#" role="button"> Get Started! &raquo;</a></p>
    </div>
    <div class="col-md-4">
	    <%= image_tag("subheader-lists.png", :alt => "", :class => "section-head") %>
      <h2>Create shopping lists</h2>
      <p> Under construction. </p>
      <p><a class="btn btn-default" href="#" role="button"> Get Started! &raquo;</a></p>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="row">
  <div class="col-md-5 col-centered">
    <div id="signup-info" >
      <h2>Join GroceryWrangler today!</h2>
      Sign up now to...
      <ul>
        <li>Manage your receipts</li>
        <li>Track your spending</li>
        <li>Follow price trends</li>
        <li>Scan your receipts</li>
      </ul>
      Membership is free!
    </div>
  </div>
  
  <div class="col-md-4 col-centered">
    <div id="signup-form" class="row">
      <%= simple_form_for(:user, :url => {:action => "create"}, html: {class: 'form-horizontal' }) do |f| %> 
      <%= render 'shared/error_messages' %>
  
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control"  %>
  
      <%= f.label :email %>
      <%= f.text_field :email, :class => "form-control" %>
  
      <%= f.label :password %>
      <%= f.password_field :password, :class => "form-control" %>
  
      <%= f.label :password_confirmation, "Password Confirmation", :class => "control-label" %>
      <%= f.password_field :password_confirmation, :class => "form-control" %>
  
      <%= f.submit "Create my account", class: "btn btn-large btn-primary", :id => "signup-submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>