config/routes.rb
GroceryWrangler::Application.routes.draw do
  get "modal/category_selection"

  root 'users#index'

  resources :users, only: [:create, :index, :new]
  resources :store_items, only: [:create, :new, :show]
  resources :sessions, only: [:create]
  resources :receipt_items, only: [:destroy]
  resources :receipts
  resources :categories

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/budgeting',    to: 'budgeting#index',                          via: 'get'
  match '/price_trend',   to: 'price_trend#index',                       via: 'get'
  match '/recipes', to: 'recipe#index',                                  via: 'get'
  match '/category_selection_dialog', to: 'categories#selection_dialog', via: 'get'

  match '/receipt_add_items', to: 'receipts#add_items', via: 'post'
  match '/receipt_items_selection_dialog', to: 'receipt_items#selection_dialog', via: 'get'
  match '/receipt_items', to: 'receipt_items#update', via: 'patch'
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  # TODO: Make sure a receipt NEVER has multiple of the same store item.
  belongs_to :store
  belongs_to :user
  has_many :receipt_items, dependent: :destroy
  validates :total, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10000000}
  validates :notes, length: { maximum: 2000 }

  def find_store_item(store_item)
    # Given a store_item it looks through the receipt for a receipt_item that
    # has the given store_item, or else it returns nil.
    if store_item.nil?
      return nil
    end

    self.receipt_items.each do |item| 
      return item if item.store_item.name == store_item.name 
    end

    return false
  end

  def add_items(store_items, params)
    @new_rec_items = []
    @items_to_update = []

    store_items.each do |store_item|
      same_rec_item = self.find_store_item(store_item)

      if same_rec_item
        same_rec_item.update_quantity(params["quantity_item_#{store_item.id}"].to_f)

        @items_to_update.append({item_id: same_rec_item.id, 
                                 quantity: same_rec_item.quantity})
      else
        @new_rec_item = ReceiptItem.new(quantity: params["quantity_item_#{store_item.id}"], 
                                        price: params["store_item_price_#{store_item.id}"], 
                                        store_item: store_item,
                                        receipt: self)

        if @new_rec_item.valid?
          @new_rec_items.push(@new_rec_item)
        else
          return false
        end
      end
    end

    return {new_rec_items: @new_rec_items, items_to_update: @items_to_update}
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :signed_in_user, only: [:add_items, :index, :new, :show]

  # POST /receipt_add_items
  def add_items
    @store_items = StoreItem.where(id: params[:item_ids])
    @items_to_update = []
    @receipt = Receipt.find(params[:receipt])
    
    items = @receipt.add_items(@store_items, params)

    unless items
        respond_to do |format|
        format.js { render 'error' and return }
      end
    end

    # This should be safe as the quantity in the database must be a number, and 
    # item_id is gathered from the database itself.
    @items_to_update = items[:items_to_update].to_json.html_safe
    @new_receipt_items = items[:new_rec_items]
    items[:new_rec_items].each {|item| item.save}
    @receipt.reload
  end

  # POST /receipts
  def create
    @receipt = Receipt.new(receipt_params)
    @receipt.user_id = current_user.id
    if @receipt.save
      flash[:success] = "Receipt created!"
      redirect_to @receipt
    else
      @errors = @receipt.errors
      render 'new'
    end    
  end

  # DELETE /receipt/#
  def destroy 
    @receipt = Receipt.find(params[:id])
    @receipt.destroy
    redirect_to receipts_url
  end

  # GET /receipts
  def index
    @receipts = Receipt.where(user_id: current_user.id)
    render layout: "receipt"
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
  end

  # GET /receipt/#
  def show
    @receipt = Receipt.find(params[:id])

    if current_users_receipt?(@receipt)
      render layout: "receipt"
    else
      flash[:errors] = "This is not your receipt!"
      redirect_to root_url
    end
  end

  private
  def current_users_receipt?(receipt)
    current_user && current_user.id == receipt.user.id
  end

  def receipt_params
    params.require(:receipt).permit(:notes, :date_purchased, :store_id)
  end

  # Before filters
  def signed_in_user
    unless signed_in?
      flash[:errors] = "Please sign in."
      redirect_to root_url
    end
  end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper

  def add_item_button
    span = content_tag(:span, "", { :class => 'glyphicon glyphicon-plus'} )
    class_string = "btn btn-primary btn-lg btn-block"
    modal_id = '#selection-modal'

    link_to_opts ={
      remote: true, 
      "data-toggle" => 'modal', 
      "data-target" => modal_id, 
      class: class_string, 
      id: 'add-item-btn'
    }

    link_to(span + "Add Item", category_selection_dialog_path(receipt: @receipt), link_to_opts)
  end

  def delete_receipt_btn(id)
    span = content_tag(:span, 
                       "", 
                       class: "glyphicon glyphicon-remove")
    class_string = "edit-item-btn btn btn-danger btn-primary btn"
    link_to(span + " Delete", receipt_path(id), method: :delete, type: "button", class: class_string, confirm: 'Are you sure you want to delete this receipt?')
  end
end

app/views/receipts/_item_table_header.html.erb
<tr>
  <th> </th>
  <th> Name </th>
  <th> Category </th>
  <th> Quantity </th>
  <th> Weight </th>
  <th> Volume </th>
  <th> Price </th>
</tr>

app/views/receipts/_receipt.html.erb
<% if receipt %>
  <div class="col-md-4">
    <div class="receipt-container">
      <%= link_to receipt, :title => "Some link" do %>
        <span class="link-spanner"></span>
        <h4>
       	  <% if receipt.store %>
       	    <%= receipt.store.name %>
       	  <% else %>
       	    Some Store
       	  <% end %>
       	</h4>
       	<h4> 
       	  <% if receipt.date_purchased %>
       	    <%= receipt.date_purchased.to_formatted_s(:long_ordinal) %>
       	  <% else %>
       	    Some Date
       	  <% end %>
       	</h4>
        <h4> $<%= price_string_format(receipt.total) %> </h4>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="col-md-4"> </div>
<% end %>

app/views/receipts/index.html.erb
<%= provide(:title, 'Receipts') %>

<% @receipts.in_groups_of(3).each do |group| %>
  <div class="row">
    <%= render partial: 'receipt', collection: group, :as => :receipt %>
  </div>
<% end %>

app/views/receipts/new.html.erb
<% provide(:title, 'Create a receipt') %>

<div class="row">
  <div id="receipt-create" class="col-md-5 col-centered">
    <%= simple_form_for(:receipt, :url => {:action => "create"}, html: {class: 'form-horizontal' }) do |f| %> 
      <%= render 'shared/error_messages' %>

      <%= f.label :date_purchased, "Date Purchased", :class => "string required control-label" %>
      <%= f.text_field :date_purchased, :class => "form-control", :data => {behaviour: 'datepicker'} %>

      <%= f.label :notes %>
      <%= f.text_area :notes, :class => "form-control border-padding"  %>

      <div class="centered-text">
        <%= f.label :store_id, "Store", :class => "string required control-label" %>
        <%= collection_select(:receipt, :store_id, Store.all, :id, :store_name, prompt: true) %>

        <%= f.submit "Create Receipt", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/receipts/show.html.erb
<%= provide(:title, 'Show Receipts') %>

<div id="receipt-jumbotron" class="jumbotron">
  <div class="container">
    <% if @receipt.store %>
      <div class="centered-text">
        <h1 id="store-name-text"> <%= @receipt.store.name %> </h1>
      </div>
    <% end %>

    <% if @receipt.date_purchased %>
      <div class="centered-text">
        <h3> <%= @receipt.date_purchased.to_formatted_s(:long_ordinal)%> </h3>
      </div>
    <% end %>
    <h3 id="receipt-total" class="centered-text"> $<%= @receipt.total %> </h3>
  </div>
</div>

<%= add_item_button %>

<%= form_for(:receipt_item, url: receipt_items_path, html: { method: :patch }, remote: true) do |f| %>
  <%= f.hidden_field :id, id: "item-id" %>
  <%= f.hidden_field :quantity, id: "item-quantity" %>
  <%= f.hidden_field :price, id: "item-price" %>
<% end %>

<table class="table table-responsive table-hover" id="receipt-item-table">
  <thead>
    <%= render partial: 'item_table_header'%>
  </thead>
  <tbody>
    <%= render partial: '/receipt_items/item_table_entry', locals: { receipt_items: @receipt.receipt_items } %>
  </tbody>
</table>