config/routes.rb
GroceryWrangler::Application.routes.draw do
  get "modal/category_selection"

  root 'users#index'

  resources :users, only: [:create, :index, :new]
  resources :store_items, only: [:create, :new, :show]
  resources :sessions, only: [:create]
  resources :receipt_items, only: [:destroy]
  resources :receipts
  resources :categories

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/budgeting',    to: 'budgeting#index',                          via: 'get'
  match '/price_trend',   to: 'price_trend#index',                       via: 'get'
  match '/recipes', to: 'recipe#index',                                  via: 'get'
  match '/category_selection_dialog', to: 'categories#selection_dialog', via: 'get'

  match '/receipt_add_items', to: 'receipts#add_items', via: 'post'
  match '/receipt_items_selection_dialog', to: 'receipt_items#selection_dialog', via: 'get'
  match '/receipt_items', to: 'receipt_items#update', via: 'patch'
end

app/views/layouts/_header.html.erb
<nav class="navbar" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div>
	<%= image_tag("logo.png", :alt => "", :class => "navbar-left", :height => "50px") %>
	<a class="navbar-brand navbar-left" href="/">GroceryWrangler</a>
      </div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->

    <% if signed_in? %>
      <div class="collapse navbar-collapse navbar-left" id="bs-example-navbar-collapse-1">
      	<ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-no-turbolink="true"> Receipts <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Receipts", receipts_path %></li>
              <li><%= link_to "Create a receipt", new_receipt_path %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-no-turbolink="true"> Items <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create an item", new_store_item_path %></li>
            </ul>
          </li>
	      </ul>
      </div>
    <% else %>
      <div class="navbar-right josecanseco-navbar-btn">
	<%= simple_form_for(:session, html: {class: 'navbar-form josecanseco-navbar-form'}, :url => sessions_path) do |f| %> 
	  <%= f.text_field :email, :class => "form-control", :placeholder => "Email"  %>
	  <%= f.password_field :password, :class => "form-control", :placeholder => "Password" %>

	  <div class="btn josecanseco-navbar-btn">
	    <%= f.submit "Login", class: "btn josecanseco-navbar-text" %>
	  </div>

	  <div class="btn josecanseco-navbar-btn">
	    <%= link_to("Sign up!", 
			signup_path,
			class: "btn josecanseco-navbar-text") %>
	<% end %>
	  </div>
      </div>
    <% end %>

    <% if signed_in? %>
      <div class="navbar-right">
	<p class="btn josecanseco-navbar-fancy-text"> Welcome <%= current_user.name %> </p>
	<div class="btn josecanseco-navbar-btn">
	  <%= link_to("Logout", 
		      signout_path,
		      class: "btn josecanseco-navbar-text",
		      method: :delete) %>
	</div>
      </div>
    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title> <%= yield(:title) %></title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    
    <div class= "container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/receipt.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %></title>
    <!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
	<![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render partial: 'shared/selection_modal' %>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <div class= "container">
      <%= yield %>
    </div>
  </body>
</html>